/**/space_panda_link:
  ros__parameters:
    enabled: True
    leader_ns: "panda"
    follower_ns: "ur20"
    damping:
      enabled: True
      value: 100.0
      force_threshold: 20.0
    wrench_passthrough: 
      enabled: True
      filter_alpha: 0.1
      force_scale: 0.6
      torque_scale: 0.4
    mimicing: 
      enabled: True
      scale: 0.3
